name: Deploy ChartFox App

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le dépôt
        uses: actions/checkout@v3

      - name: 🔧 Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 📦 Installer les dépendances
        run: npm install

      - name: 🛠️ Générer le fichier .env avec le secret
        run: echo "CHARTFOX_TOKEN=${{ secrets.CHARTFOX_TOKEN }}" > .env

      - name: 🚀 Déployer (exemple avec Render)
        run: |
          curl -X POST https://api.render.com/deploy/srv-xxxxxx?key=TON_WEBHOOK_SECRET
