      - name: Commit and push charts JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/charts-*.json
          git commit -m "Add charts data for ${{ github.event.inputs.icao }}" || echo "No changes to commit"
          git push
