      - name: Fetch charts from ChartFox
        env:
          CHARTFOX_TOKEN: ${{ secrets.CHARTFOX_TOKEN }}
        run: |
          icao=${{ github.event.inputs.icao }}
          echo "Fetching charts for $icao"

          response=$(curl -L -s \
            -H "Authorization: Bearer $CHARTFOX_TOKEN" \
            -H "Accept: application/json" \
            "https://chartfox.org/api/airport/$icao")
          mkdir -p data
          echo "$response" > data/charts-$icao.json
