name: Fetch ChartFox Charts

on:
  workflow_dispatch:
    inputs:
      icao:
        description: "Code OACI de l'aéroport (ex: LFPG)"
        required: true

jobs:
  fetch_charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Récupérer les données ChartFox
        env:
          CHARTFOX_TOKEN: ${{ secrets.CHARTFOX_TOKEN }}
        run: |
          ICAO=${{ github.event.inputs.icao }}
          echo "Fetching charts for $ICAO..."
          RESPONSE=$(curl -s -L \
            -H "Authorization: Bearer $CHARTFOX_TOKEN" \
            -H "Accept: application/json" \
            "https://chartfox.org/api/airport/$ICAO")

          echo "$RESPONSE" | jq . > /dev/null || exit 5

          mkdir -p data
          echo "$RESPONSE" > "data/charts-$ICAO.json"

      - name: Commit et push des données
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/charts-*.json
          git commit -m "Ajout des cartes pour ${{ github.event.inputs.icao }}" || echo "Pas de changement"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
