name: Fetch ChartFox Charts

on:
  workflow_dispatch:
    inputs:
      icao:
        description: 'Code OACI'
        required: true
        default: 'LFPG'

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Fetch charts from ChartFox
        env:
          CHARTFOX_TOKEN: ${{ secrets.CHARTFOX_TOKEN }}
        run: |
          icao=${{ github.event.inputs.icao }}
          echo "Fetching charts for $icao"

          response=$(curl -s -H "Authorization: Bearer $CHARTFOX_TOKEN" "https://chartfox.org/api/airport/$icao")
          mkdir -p data
          echo "$response" > data/charts-$icao.json

      - name: Commit and push charts JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/charts-*.json
          git commit -m "Add charts data for ${{ github.event.inputs.icao }}" || echo "No changes to commit"
          git push
